server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://223.130.163.223:3306/study
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
       hibernate:
         show_sql: false
         format_sql: true
         highlight_sql: true

logging:
  pattern:
    console: "[%d{HH:mm:ss:SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
        SQL: debug

REST_API_KEY: "4b87640351e515653ed429a9fdb7eb32"